name: shabadabada
description: A mobile implementation of the french card game Shabadabada

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_i18n: ^0.32.3
  logger: ^1.1.0
  collection: ^1.16.0
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.1.13
  multi_value_listenable_builder: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  r_flutter: ^0.9.0
  json_locale_generator: ^0.0.3
  injectable_generator: ^1.5.3


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/locales/

json_to_dart:
  sample_files:
    - source: assets/locales/en.json
      class_name: Locales
